# Generated by Django 5.0.4 on 2024-04-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='foods.RecipeIngredient', to='foods.ingredient', verbose_name='Ingredients for recipe'),
        ),
    ]
