# Generated by Django 5.0.4 on 2024-04-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_recipe_ingredients'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='only_one_ingredient_for_recipe'),
        ),
    ]