# Generated by Django 5.0.4 on 2024-04-15 16:28
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_rename_owner_favorite_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-id']},
        ),
        TrigramExtension(),
    ]