# Generated by Django 5.0.4 on 2024-04-20 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Time of cooking cant be less than 1 minute'), django.core.validators.MaxValueValidator(limit_value=32000, message='Time of cooking cant be more than 32 000 minutes')], verbose_name='Time of cooking recipe in minutes'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Amount must be at least 1'), django.core.validators.MaxValueValidator(limit_value=32000, message='Max amount size cant be                   more than 32 000 mesurement of unit!')]),
        ),
    ]
