version: '3'

volumes:
  static:
  media:
  pg_data_foodgram:

services:

  db:
    image: postgres:13.0
    volumes:
      - pg_data_foodgram:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always

  backend:
    image: kaluginpeter/foodgram_backend:latest
    restart: always
    volumes:
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: kaluginpeter/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
      - static:/var/html/static/
      - media:/var/html/media/
    depends_on:
      - backend
    restart: always